// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_AddPassword
SEXP R_AddPassword(const std::string& service, const std::string& account, const std::string& password);
RcppExport SEXP keyring_R_AddPassword(SEXP serviceSEXP, SEXP accountSEXP, SEXP passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type service(serviceSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type account(accountSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type password(passwordSEXP);
    __result = Rcpp::wrap(R_AddPassword(service, account, password));
    return __result;
END_RCPP
}
// R_GetPassword
SEXP R_GetPassword(const std::string& service, const std::string& account);
RcppExport SEXP keyring_R_GetPassword(SEXP serviceSEXP, SEXP accountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type service(serviceSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type account(accountSEXP);
    __result = Rcpp::wrap(R_GetPassword(service, account));
    return __result;
END_RCPP
}
// R_DeletePassword
SEXP R_DeletePassword(const std::string& service, const std::string& account);
RcppExport SEXP keyring_R_DeletePassword(SEXP serviceSEXP, SEXP accountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type service(serviceSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type account(accountSEXP);
    __result = Rcpp::wrap(R_DeletePassword(service, account));
    return __result;
END_RCPP
}
// R_FindPassword
SEXP R_FindPassword(const std::string& service);
RcppExport SEXP keyring_R_FindPassword(SEXP serviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type service(serviceSEXP);
    __result = Rcpp::wrap(R_FindPassword(service));
    return __result;
END_RCPP
}
