# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_AddPassword <- function(service, account, password) {
    .Call('keyring_R_AddPassword', PACKAGE = 'keyring', service, account, password)
}

R_GetPassword <- function(service, account) {
    .Call('keyring_R_GetPassword', PACKAGE = 'keyring', service, account)
}

R_DeletePassword <- function(service, account) {
    .Call('keyring_R_DeletePassword', PACKAGE = 'keyring', service, account)
}

R_FindPassword <- function(service) {
    .Call('keyring_R_FindPassword', PACKAGE = 'keyring', service)
}

