# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_AddPassword <- function(service, account, password) {
    .Call('keyring_R_AddPassword', PACKAGE = 'keyring', service, account, password)
}

R_GetPassword <- function(service, account) {
    .Call('keyring_R_GetPassword', PACKAGE = 'keyring', service, account)
}

R_DeletePassword <- function(service, account) {
    .Call('keyring_R_DeletePassword', PACKAGE = 'keyring', service, account)
}

R_FindPassword <- function(service) {
    .Call('keyring_R_FindPassword', PACKAGE = 'keyring', service)
}

R_AddInternetPassword <- function(servername, account, port, password) {
    .Call('keyring_R_AddInternetPassword', PACKAGE = 'keyring', servername, account, port, password)
}

R_GetInternetPassword <- function(servername, account, port) {
    .Call('keyring_R_GetInternetPassword', PACKAGE = 'keyring', servername, account, port)
}

R_DeleteInternetPassword <- function(servername, account, port) {
    .Call('keyring_R_DeleteInternetPassword', PACKAGE = 'keyring', servername, account, port)
}

R_FindInternetPassword <- function(servername, port) {
    .Call('keyring_R_FindInternetPassword', PACKAGE = 'keyring', servername, port)
}

